version: '3'
services:
  # Used to run a server to be used by test
  server:
    image: python:3.7-buster
    volumes:
      - ./public:/app/public:ro
    ports:
      - '8000'
    command: bash -c "cd /app/public && python -m http.server 8000"

  # Allow to run scrap tests before deployment
  test:
    build: tests
    volumes:
      - ./tests/src:/app/src:ro
      - ./tests/package.json:/app/package.json:ro
    command: yarn test
    depends_on:
      - server
