services:
  # Use to build project
  doc:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src:ro
      - ./scripts:/app/scripts:ro
      - ./content:/app/content
      - ./website/release-notes:/app/website/release-notes:ro
      - ./website/blog:/app/website/blog:ro
      - ./website/uc-doc:/app/website/uc-doc:ro
      - ./.prettierrc:/app/.prettierrc:ro
      - ./.prettierignore:/app/.prettierignore:ro
      - ./static:/app/static:ro
      - ./gatsby-node.js:/app/gatsby-node.js:ro
      - ./gatsby-config.js:/app/gatsby-config.js:ro
      - ./config.js:/app/config.js:ro
      - ./tests:/app/tests:ro
      - ./Makefile:/app/Makefile:ro
    command: sleep 3600 # Use to let container up during build
