---
- hosts: all
  tasks:
    - name: Set log path for a change
      when: zuul.change is defined
      set_fact:
        zuul_log_path: '{{ zuul.change[-2:] }}/{{ zuul.change }}/{{ zuul.patchset }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}'

    - name: Set log path for a ref update
      when: zuul.newrev is defined
      set_fact:
        zuul_log_path: '{{ zuul.newrev[-2:] }}/{{ zuul.newrev }}/{{ zuul.pipeline }}/{{ zuul.job }}/{{ zuul.build[:7] }}'

    - name: Prepare config.js
      copy:
        content: |
          module.exports = {
            githubToken: '',
            algolia: {
              appId: '',
              publicKey: '',
              apiKey: '',
            },
          };
        dest: '{{ zuul.project.src_dir }}/config.js'

    - name: make
      command: 'make'
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: make build
      command: 'make build'
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: make test
      command: 'make test'
      args:
        chdir: '{{ zuul.project.src_dir }}'

    - name: Add resulting site to job's logs
      synchronize:
        src: '{{ zuul.project.src_dir }}/public'
        dest: '{{ zuul.executor.log_root }}'
        mode: pull
        copy_links: true
        verify_host: true
        rsync_opts:
          - --prune-empty-dirs
